### ISSUE TITLE
Errors on glibc when trying to link with FFmpeg builds for Linux

### ISSUE THREAD

**Issue by nejatafshar** [wang-bin/avbuild#32]
Using the builds `ffmpeg-4.2-linux-gcc-lite.tar.xz` and `ffmpeg-4.1-linux-gcc-lite.tar.xz` for Linux in sourceforge gives me this error related to glibc:
```
libavcodec.so: undefined reference to `powf@GLIBC_2.27'
libavformat.so: undefined reference to `glob64@GLIBC_2.27'
libavcodec.so: undefined reference to `log2f@GLIBC_2.27'
libavcodec.so: undefined reference to `expf@GLIBC_2.27'
libavcodec.so: undefined reference to `exp2f@GLIBC_2.27'
libavcodec.so: undefined reference to `logf@GLIBC_2.27'
```
Where as using `ffmpeg-4.0.3-linux-gcc-lite.tar.xz` compiles normally.
It seems that the newer versions are built against glibc 2.27, while I have glibc 2.23 on my Ubuntu 16.04. Is there any solution to this?

**Comment by wang-bin** [comment]
No trival solution. symbol versioning and dso versioning are holy ****. It's unfriendly for developers to keep backward compatibility. You can modify `#define HAVE_LOG2 1` in generated config.h. But even if those symbols are found, libavcodec and libavutil won't be loaded on ubuntu 16.04, because they depend on libva.so.2, which only exist on new ubuntu.

**Comment by wang-bin** [comment]
you can build on ubuntu 16.04 yourself, new vaapi won't be available.

**Comment by wang-bin** [comment]
musl libc may solve glibc issue. not tested

**Comment by nejatafshar** [comment]
@wang-bin Thanks for the useful info. I compile and deploy all of my Linux apps on Ubuntu 16.04 to make them run on all distros newer than that. Actually it's a recommended practice by LinuxDeployQt and AppImage. But it's not always straightforward to use latest versions of libs while developing. I managed to install newest vaapi on my Ubuntu 16.04. So it's better to compile FFmpeg on my own.
